// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkllskohryqgbfxtnnli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rbGxza29ocnlxZ2JmeHRubmxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMDk3MzMsImV4cCI6MjA1MjY4NTczM30.dON7UOCyMahwllNjsfaHymBKkH5BSvU84NeYjIM8bdQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);